server:
  port: 8082

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: seu email
    password: sua senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com