server:
  port: 8082

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: eduardo.eesf@gmail.com
    password: flos ybal sgck fncx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com